import { useRef, useEffect } from "react";
import "./RawDiagramBlock.css";

// ---------------------------------------------------------------------------
// RawDiagramBlock
//
// Renders a self-contained HTML diagram generated by AI inside a sandboxed
// iframe. The HTML is authored using Cytoscape.js following DIAGRAM_RULES.md.
//
// Workflow:
//   1. Hand DIAGRAM_RULES.md + your node/edge data to Claude (or any AI).
//   2. It returns a complete self-contained HTML file.
//   3. Paste that HTML into the "Diagram HTML" field in Sanity.
//   4. This component renders it — pan/zoom/drag/mobile all handled by Cytoscape.
//
// Props:
//   heading     string?  — gold eyebrow label
//   caption     string?  — note below
//   html_code   string   — the generated HTML
//   height      number   — iframe height in px (default 560)
// ---------------------------------------------------------------------------

export default function RawDiagramBlock({
  heading,
  caption,
  html_code,
  height = 560,
}) {
  const iframe_ref = useRef(null);

  // Use a Blob URL so CDN script tags inside the HTML load reliably
  // across all browsers (some block CDN loads in srcdoc iframes).
  useEffect(() => {
    if (!iframe_ref.current || !html_code) return;

    const blob = new Blob([html_code], { type: "text/html" });
    const url  = URL.createObjectURL(blob);
    iframe_ref.current.src = url;

    return () => URL.revokeObjectURL(url);
  }, [html_code]);

  if (!html_code) return null;

  return (
    <div className="rdb-block">

      {heading && (
        <div className="rdb-heading">
          <span className="rdb-heading-text">{heading}</span>
        </div>
      )}

      <div className="rdb-frame-wrap" style={{ height }}>
        <iframe
          ref={iframe_ref}
          className="rdb-frame"
          title={heading ?? "Architecture diagram"}
          sandbox="allow-scripts allow-same-origin"
          loading="lazy"
          /* src is set by the effect above */
        />
      </div>

      {caption && <p className="rdb-caption">{caption}</p>}

    </div>
  );
}
